FROM ubuntu
RUN apt-get update
RUN ["apt-get" , "install" , "figlet"]
CMD ["figlet", "-f", "script", "hello"]
# ENTRYPOINT ["figlet", "-f", "script"]


# ENTRYPOINT ["figlet", "-f", "script"]

# CMD ["hello"]



# CMD ["figlet", "-f", "script", "hello"]

FROM ubuntu
RUN apt-getupdate
RUN ["apt-get", "install", "figlet"]
CMD ["figlet","-f","script", "hello"]

docker build -t figlet:v1 .

FROM ubuntu
RUN apt-getupdate
RUN ["apt-get", "install", "figlet"]
ENTRYPOINT ["figlet", "-f" , "script" ]
CMD ["hello"]
